### ISSUE TITLE
Website Code

### ISSUE THREAD

**Issue by devt204** [mukundsrinath/CoLiPPS#1]
Hi I've just found one of my website code listed in the project, can I understand the significance of adding the website code to the repo

https://github.com/mukundsrinath/CoLiPPS/blob/302e61cbfe8b3ad821c3ed15a0a7af282d4204da/data/7/c54a801d8d4c5956125766f10554a4d19a351966.html

**Comment by mukundsrinath** [comment]
This is a corpus of privacy polices. Apologies for any issues this caused. I have deleted the file.
