### ISSUE TITLE
Using Company Website Code

### ISSUE THREAD

**Issue by richardaowens** [mukundsrinath/CoLiPPS#2]
Hello you have stolen our website code and uploaded it here, which has exposed Google API keys. 

Why are you doing this?

Please remove this entire file:
https://github.com/mukundsrinath/CoLiPPS/blob/main/data/1/612bcb784c3b8cab5d756407a02e011d748800c8.html

Stop scraping others websites and uploading to public repositories, please.

**Comment by mukundsrinath** [comment]
This is a corpus of privacy polices. Apologies for any issues this caused. I have deleted the file.
